Kernel panic in run: PANIC at ../../threads/synch.c:232 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0xc0029c86 0x6c65725f
Translation of call stack:
In kernel.o:
0xc0029c86: debug_panic (.../../lib/kernel/debug.c:38)
0x6c65725f: (unknown)
